### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by mousebrains** [jessecusack/perturb#11]
Please educate me, what do you mean by "Please use pull requests."

**Comment by jessecusack** [comment]
This is a pretty good description of the pull request workflow:

https://medium.com/@urna.hybesis/pull-request-workflow-with-git-6-steps-guide-3858e30b5fa4

Essentially, you make a git branch in your local code repository and push the branch to GitHub when you've finished making edits. After doing this, you should see the 'make a pull request' button displayed on GitHub.

I will make a contributing guide to explain this in more details.

**Comment by jessecusack** [comment]
@mousebrains referencing this issue in my pull request comment allows me to automatically close the issue (see the little note above)
