### ISSUE TITLE
p files flagged

### ISSUE THREAD

**Issue by jessecusack** [jessecusack/perturb#15]
I'm trying to run perturb on the glider p files and the `qUse` parameter is set to false somewhere, so none of the p files are processed. I cannot yet figure out why... 

Ok, it was because `my_joiner` prefers the rhs table over the lhs and for some reason the rhs table was full of `qUse = false`. The rhs is loaded from `info.p2mat_filename`... I am not sure how or when this was created with so many falses.

**Comment by mousebrains** [comment]
Can you post your main routine and an ls of your P files. Also, the log file would be useful.

**Comment by jessecusack** [comment]
I kind of solved this by deleting `profileInfo.mat` and rerunning the code, but I'll leave the issue open in case a similar issue comes up.

**Comment by mousebrains** [comment]
This is dramatically cleaned up in the refactor and parallelization.

**Comment by jessecusack** [comment]
Great, I'll join this issue to the PR.
