### ISSUE TITLE
Random string in folder name

### ISSUE THREAD

**Issue by jessecusack** [jessecusack/perturb#18]
@mousebrains can you remind me why we append a random string to some of the output filenames?

**Comment by mousebrains** [comment]
It is not a random string, it is a hash of the configuration parameters.

One of the issues I've encountered is people change the configuration parameters, without wiping out all the data processed with the previous set of configuration parameters. Using the hash eliminates this problem.

I looked at more "human understandable" options, but I didn't find any. I don't remember if I've done this yet, but my plan had been to create a JSON/text version of the configuration options that go into the signature within the directory, so a human can understand how the directory was created.

This only becomes an issue if one allows for marginal analysis. i.e. if one adds P files, then one only needs to process the new stuff. This is the typical mode on ship.

**Comment by jessecusack** [comment]
The JSON/text solution is the right way to go because, like you say, it is human readable. I would do this an append a number like 001, 002 etc. to the folder if needed.

**Comment by mousebrains** [comment]
Let me think about the number versus hash. The hash is "easy," in that I don't have to look in each directory with a number to figure out if it is the correct directory.

**Comment by jessecusack** [comment]
Can you store the hash within the directory?

If only matlab supported YAML, all this config stuff would be a lot easier.

**Comment by mousebrains** [comment]
The hash would definitely be there, in case the user "hand edits" the JSON/text. I'll have to explicitly check that the hash of the JSON/text matches the version I've stored.

Having multiple directories is not a big deal, as long as the number is in the handful range, not thousands.

That being said, a method would be to save the hash as part of the JSON/text filename. i.e. something like:

config.712fdeaf.json

Then I can use dir with the appropriate wildcard to pull it out.

**Comment by jessecusack** [comment]
I opened a second matlab instance and ran the same parameters yet it created a new profiles folder. I thought that the hash sum would be the same because the parameters are the same. I don't understand how this is working...

**Comment by mousebrains** [comment]
Changed in upcoming refactoring and parallelization

**Comment by jessecusack** [comment]
Great, linked to PR.
