### ISSUE TITLE
Epsilon estimated from separate shear probes in binned data?

### ISSUE THREAD

**Issue by jessecusack** [jessecusack/perturb#20]
It seems that the binned data (and therefore the combo netcdf) does not contain separate estimates of epsilon from the two shear probes. I haven't figured out where they get dropped, but they should be outputted. How would we change this?

**Comment by jessecusack** [comment]
@mousebrains I think this is happening in the netcdf creation step. My current guess is because `e_diss` is a 2 x n matrix, only the first column is being saved so really we're only seeing shear probe 1 data.

**Comment by mousebrains** [comment]
#22 Exposed individual shear probe data

**Comment by mousebrains** [comment]
Here is an example for a VMP cast from the combo file:
![paraJesse](https://github.com/jessecusack/perturb/assets/3686892/14e6d665-f478-4d98-94d0-fb3d0b71d892)
