### ISSUE TITLE
Trimming surface data?

### ISSUE THREAD

**Issue by jessecusack** [jessecusack/perturb#21]
When I run `quick_look` on some of our data, I can get epsilon estimates to within 2 m of the surface. From looking at the combo file, it looks like surface data is being dropped by our processing. Where in the code do you think this might be happening?

**Comment by mousebrains** [comment]
In my results, I get data up to 1m.

**Comment by jessecusack** [comment]
Can you copy paste your configuration file here?

**Comment by mousebrains** [comment]
What do you mean by configuration? My main Matlab script for MR processing, only minimally tuned, is in examples/ARCTERX_MR_2023.m There still needs to be some tuning for getting the profiles unbroken, since a few casts have them broken up for a reason, yet to be understood.

**Comment by jessecusack** [comment]
This plot compares the output of `quick_look` using `ql_info.profile_min_W = 0.1;` with the output of the perturb combo file using the same vertical velocity threshold. `quick_look` produces epsilon to shallower depths. peturb seems to be biased low compared to quick_look, sometimes by an order of magnitude.

![quick_look_vs_perturb](https://github.com/jessecusack/perturb/assets/6222580/b04cf3df-837a-4b62-8630-8bd0f6d2a652)

**Comment by jessecusack** [comment]
This issue was solved by setting the parameter `trim_use = false`
