### ISSUE TITLE
add original filename to combo output

### ISSUE THREAD

**Issue by jessecusack** [jessecusack/perturb#25]
It would be super helpful to add a variable to the combined output that contained the original data file name for each profile. That would make it super easy to go back and investigate suspect profiles in detail. If it could also include the profile number, that would be extra helpful.

**Comment by mousebrains** [comment]
In the combo info table, the name column allows you to understand the files that lead to that profile. The index column is the profile number within the profiles.

**Comment by jessecusack** [comment]
I guess I specifically meant the netCDF output.

**Comment by mousebrains** [comment]
Fixed in a patch I just pushed to the main branch. I had explicitly dropped them since one can't compress strings in Matlab's NetCDF interface. I now have a check if the variable is a string, in which case it doesn't tell NetCDF to compress the variable.

**Comment by mousebrains** [comment]
In the previous version I had the absolute filenames. I took that away in this version and just use the base name, sans suffix, as an overall key through the various tables. This was to cleanly handle shipboard use where multiple people will be running marginal updates and their paths may be different on their individual systems.
