### ISSUE TITLE
combo netcdf date_created attribute not in UTC

### ISSUE THREAD

**Issue by jessecusack** [jessecusack/perturb#29]
The `date_created` attribute indicates UTC but appears to be local time. Same for modified, issued, etc.

**Comment by mousebrains** [comment]
Thanks, I'll dig into it tomorrow. I'll merge the current pull request and branch out for digging explicitly through the timezone management.

**Comment by mousebrains** [comment]
Fixed via a hot patch to nc_add_global_attribute.m.
